# Generated by Django 5.0.2 on 2024-02-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('prodect_description', models.TextField(max_length=150)),
                ('num_in_inventory', models.CharField(max_length=150)),
                ('product_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
