# Generated by Django 5.0.2 on 2024-02-22 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_name', models.CharField(max_length=100)),
                ('inventory_type', models.CharField(max_length=100)),
                ('inventory_description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='num_in_inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
    ]
