# Generated by Django 5.0.2 on 2024-02-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prodect_description',
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(default=None),
        ),
    ]
